name: Compilar APK de Flet

on:
  push:
    branches: [ main, principal ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Compilar APK
        run: |
          flet build apk main.py --verbose --yes

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/apk/app-release.apk
          
