name: Compilar APK de Flet

on:
  push:
    branches: [ main, principal ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Revisar el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet
        run: |
          pip install flet

      - name: Compilar APK
        run: |
          flet build apk main.py --yes

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/apk/app-release.apk
          
